#!/usr/bin/python
# -*- coding: utf-8 -*-

import MySQLdb as mdb

connect = mdb.connect('192.168.1.4', 'jose', 'jose', 'hotel');

with connect:

    cur = connect.cursor()
    cur.execute("SELECT * FROM Estancias")

    for i in range(cur.rowcount):
        
        registro = cur.fetchone()
        print registro[0], registro[1]
